from itertools import chain
import sys

from .options import get_parser, parse_args, validate


NAME = 'deps2dot'

HEADER = """\
# Generated by deps2dot, https://github.com/tartley/deps2dot
"""

def print_output(dot_lines):
    print(HEADER)
    for line in dot_lines:
        print(line)


def deps_to_dot(node):
    yield node.start
    #for child in node.children:
        #yield deps_to_dot(child)
    yield node.end


class RootNode(object):
    start = """\
digraph esperanto {

    graph [
    ]

    node [
    ]
"""

    end = """\
}
"""


def read_file(filename):
    with open(filename) as filepointer:
        for line in filepointer:
            yield eval(line)

    
def read_deps(options):
    deps = RootNode()
    for line in read_file(options.input):
        (start_root, start_name), (end_root, end_name) = line
    return deps


def main():
    # setup.py install/develop creates an executable that calls this function
    print_output(
        deps_to_dot(
            read_deps(
                validate(
                    parse_args(
                        get_parser(NAME),
                        sys.argv[1:]
                    )
                )
            )
        )
    )
